import { Noto_Sans_JP } from 'next/font/google'
import './globals.css'

// 1. フォントの読み込み
const NotoSansJP = Noto_Sans_JP({
  weight: ["400", "700"],
  subsets: ["latin"],
  preload: true,
});


// 1. ページのメタデータ
export const metadata = {
  title: 'Next.js Awesome Memo App',
  description: 'Generated by create next app',
}

// 2. ページのレイアウト
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ja">
      {/* 3. ページやレイアウトの内容を表示 */}
      <header>
        <nav>
          <ul>
            <li><a href="/">Home</a></li>
            <li><a href="/about">About</a></li>
            <li><a href="/contact">Contact</a></li>
          </ul>
        </nav>
      </header>
      <main>{children}</main>
      <footer>
        <p>&copy; {new Date().getFullYear()} Sample Site. All rights reserved.</p>
      </footer>
    </html>
  )
}